import config_themes

# globals
NL = "\n"

# extensions
ALLOWED_EXTENSIONS = ("png", "jpg", "jpeg")

# style base
DEFAULT_FONT = "Arial"
DEFAULT_WINDOW_WIDTH = 850
DEFAULT_WINDOW_HEIGHT = 700

DEFAULT_JOURNAL_WIDTH = 700
DEFAULT_JOURNAL_HEIGHT = 350

DEFAULT_FORMULA_INPUT_WIDTH = 500
DEFAULT_FORMULA_INPUT_HEIGHT = 150

DEFAULT_THEME_SELECT_WIDTH = 700
DEFAULT_THEME_SELECT_HEIGHT = 350

DEFAULT_BINDERS_WIDTH = 400
DEFAULT_BINDERS_HEIGHT = 150

TOPBAR_SIZE = 20
TOPBAR_MENU_BUTTON_SIZE = 22

# default detection parameters
DEFAULT_THRESHOLD_MIN = 160
DEFAULT_THRESHOLD_MAX = 255
DEFAULT_GLARE_BARRIER = 230
DEFAULT_GLARE_CEILING = 255
DEFAULT_GLARE_BLUR = 7
DEFAULT_AREA_MIN = 20
DEFAULT_AREA_MAX = 800
DEFAULT_AREA_BASE = 330
DEFAULT_AREA_RATIO = 0.7
DEFAULT_KSIZE = 9
DEFAULT_PROP_SIZE = 120
DEFAULT_AREA_SIZE = 50

# style
MAIN_STYLE = {}
for c in config_themes.__dict__:
    if "collection" in c:
        coll = config_themes.__dict__[c]
        for k in coll:
            MAIN_STYLE[k] = coll[k]
STYLES = config_themes.theme_order

CANVAS_HIGHLIGHT_THICKNESS = 2
RESULT_CANVAS_HIGHLIGHT_THICKNESS = 2

COLOR_PICKER_RADIUS = 15
COLOR_PICKER_WIDTH = 5

# canvas rendering style
CANVAS_AREA_START_FILL = "#0000ff"
CANVAS_AREA_START_OUTLINE = "#ffffff"
CANVAS_AREA_START_SIZE = 7
CANVAS_AREA_START_WIDTH = 1

CANVAS_AREA_END_FILL = "#ffff00"
CANVAS_AREA_END_OUTLINE = "#000000"
CANVAS_AREA_END_SIZE = 7
CANVAS_AREA_END_WIDTH = 1

CANVAS_AREA_MIDPOINT_FILL = "#999999"
CANVAS_AREA_MIDPOINT_OUTLINE = "#101010"
CANVAS_AREA_MIDPOINT_SIZE = 7
CANVAS_AREA_MIDPOINT_WIDTH = 1

CANVAS_DETECTION_COLOR = "#00ff00"
CANVAS_DETECTION_WIDTH = 2
CANVAS_DETECTION_TEXT_SIZE = 10
CANVAS_DETECTION_TEXT_COLOR = "#550055"

# statuses
STATUS_LABEL_COLOR = "#ffffff"
STATUSES = {
    "status": ["#000055", "STATUS"],
    "info": ["#003355", "INFO"],
    "warninfo": ["#332255", "WARNINFO"],
    "prompt": ["#445555", "PROMPT"],
    "success": ["#005511", "SUCCESS"],
    "warning": ["#554400", "WARNING"],
    "error": ["#550000", "ERROR"],
    "criterror": ["#550055", "CRITERROR"]
}

# default debug values
SHOW_DEBUG_IMAGES = False
FILTER_GLARE = True
GLARE_RANGE = True
GLARE_FILL = True
RGB_CONVERT = False
HSV_OVER_GRAY = True
JOURNAL_MAX_MEMORY = 150 # unused
